name: u_nas_dziala_hackathon_2024
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  firebase_core: ^3.6.0
  dartz: ^0.10.1
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  get_it: ^8.0.0
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
